"""
Bootstrap Script for BitRich
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This script helps set up the BitRich application by:
- Collecting required API credentials
- Creating a .env file with environment variables
- Providing instructions for running the application

Usage:
    python bootstrap.py
"""

import os
import secrets


def get_input(prompt: str, required: bool = True, secret: bool = False) -> str:
    """Get user input with validation."""
    while True:
        if secret:
            import getpass
            value = getpass.getpass(prompt)
        else:
            value = input(prompt)
        
        value = value.strip()
        
        if value or not required:
            return value
        
        print("This field is required. Please try again.")


def main():
    """Run the bootstrap process."""
    print("""
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║   Welcome to BitRich Setup!                                   ║
║                                                               ║
║   This script will help you configure your environment.       ║
║                                                               ║
║   NOTE: This is a joke application. Do not invest real money. ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
    """)
    
    # Generate a secure secret key
    secret_key = secrets.token_hex(32)
    
    print("\n📧 Email Configuration (SendGrid)")
    print("-" * 40)
    sendgrid_api_key = get_input(
        "Enter your SendGrid API Key (or press Enter to skip): ",
        required=False
    )
    from_email = get_input(
        "Enter the 'From' email address (or press Enter for default): ",
        required=False
    ) or "noreply@bitrich.example.com"
    
    print("\n💳 Payment Configuration (Stripe)")
    print("-" * 40)
    stripe_secret = get_input(
        "Enter your Stripe Secret Key (or press Enter to skip): ",
        required=False
    )
    stripe_publishable = get_input(
        "Enter your Stripe Publishable Key (or press Enter to skip): ",
        required=False
    )
    
    print("\n₿ Crypto Configuration (Optional)")
    print("-" * 40)
    coinbase_api = get_input(
        "Enter your Coinbase API Key (or press Enter to skip): ",
        required=False
    )
    
    # Create the .env file
    env_content = f"""# BitRich Environment Configuration
# Generated by bootstrap.py - Update values as needed

# Flask Configuration
FLASK_APP=app.py
FLASK_ENV=development
SECRET_KEY={secret_key}

# Database (SQLite by default, change for production)
DATABASE_URL=sqlite:///bitrich.db

# SendGrid Email Configuration
SENDGRID_API_KEY={sendgrid_api_key}
DEFAULT_FROM_EMAIL={from_email}

# Stripe Payment Configuration
STRIPE_SECRET_KEY={stripe_secret}
STRIPE_PUBLISHABLE_KEY={stripe_publishable}

# Coinbase API (for exchange rates)
COINBASE_API_KEY={coinbase_api}
"""
    
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    
    # Check if .env already exists
    if os.path.exists(env_path):
        overwrite = get_input(
            "\n⚠️  A .env file already exists. Overwrite? (y/N): ",
            required=False
        ).lower()
        if overwrite != 'y':
            print("\nKeeping existing .env file.")
            print_instructions()
            return
    
    with open(env_path, 'w', encoding='utf-8') as f:
        f.write(env_content)
    
    print(f"\n✅ Created .env file at: {env_path}")
    print_instructions()


def print_instructions():
    """Print setup completion instructions."""
    print("""
╔═══════════════════════════════════════════════════════════════╗
║                     Setup Complete!                           ║
╚═══════════════════════════════════════════════════════════════╝

To run the application:

1. Install dependencies:
   $ pip install -r requirements.txt

2. Initialize the database:
   $ flask init-db

3. Run the development server:
   $ flask run

4. Visit http://localhost:5000 in your browser

Additional commands:
   $ flask list-users      # List all users
   $ flask create-user EMAIL PASSWORD  # Create a user
   $ flask sell-or-not     # Check investment limits

For production deployment, update:
   - FLASK_ENV=production in .env
   - Use a proper database (PostgreSQL recommended)
   - Use gunicorn: gunicorn app:app

Questions? Check the README.md for more information.
""")


if __name__ == '__main__':
    main()
